// <auto-generated />
namespace MyBookingRoles.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Order_Alter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_Alter));
        
        string IMigrationMetadata.Id
        {
            get { return "202010281111043_Order_Alter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
